import { ArtifactStorage } from "../artifacts/artifact-storage.ts";
import { ControlPlaneDatabase } from "../db/database.ts";
import { EventHub } from "../events/event-hub.ts";
import { MissionService } from "../missions/mission-service.ts";
import { SettingsService } from "../settings/settings-service.ts";
import { safeHash } from "../tasks/task-service.ts";
import { uuidv7 } from "../../../../packages/contracts/src/index.ts";

type Row = Record<string, any>;
type JsonObject = Record<string, unknown>;
type OperationState = "ACCEPTED" | "RUNNING" | "APPLIED" | "REJECTED" | "UNKNOWN" | "CANCELLED";

const parseJson = (value: unknown, fallback: unknown = {}): any => { try { return value === null || value === undefined ? fallback : JSON.parse(String(value)); } catch { return fallback; } };
const iso = (value: unknown): string | null => typeof value === "number" ? new Date(value).toISOString() : null;
const object = (value: unknown, field: string): JsonObject => { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error(`INVALID_FIELD:${field}`); return value as JsonObject; };
const text = (value: unknown, field: string, max = 500): string => { if (typeof value !== "string" || value.trim().length === 0 || value.length > max) throw new Error(`INVALID_FIELD:${field}`); return value; };
const optionalText = (value: unknown, field: string, max = 500): string | null => value === undefined || value === null ? null : text(value, field, max);
const boundedInt = (value: unknown, field: string, fallback: number, max: number): number => value === undefined ? fallback : typeof value === "number" && Number.isInteger(value) && value >= 0 && value <= max ? value : (() => { throw new Error(`INVALID_FIELD:${field}`); })();
const rejectUnknown = (value: JsonObject, allowed: readonly string[], context: string): void => { for (const key of Object.keys(value)) if (!allowed.includes(key)) throw new Error(`UNKNOWN_FIELD:${context}.${key}`); };

export type AgentWorkOptions = { db: ControlPlaneDatabase; events: EventHub; settings: SettingsService; artifacts: ArtifactStorage; missions?: MissionService };

/**
 * Control Plane authority for the Personal Agent Work additions.
 *
 * This service deliberately stops at the cross-service boundary. Hermes and a
 * browser broker must return a typed receipt before a pending binding/session
 * becomes effective; a configured URL or feature flag is not treated as proof
 * that the remote capability exists.
 */
export class AgentWorkService {
  readonly db: ControlPlaneDatabase;
  private readonly events: EventHub;
  private readonly settings: SettingsService;
  private readonly artifacts: ArtifactStorage;
  private readonly missions?: MissionService;

  constructor(options: AgentWorkOptions) { this.db = options.db; this.events = options.events; this.settings = options.settings; this.artifacts = options.artifacts; this.missions = options.missions; }

  capabilities(): Record<string, unknown> {
    const configured = this.settings.get() as Row;
    const hermes = Boolean(process.env.PAI_HERMES_OFFICE_URL);
    const make = (flag: string, dependency: boolean, reason: string) => ({ configured: configured[flag] === true, available: configured[flag] === true && dependency, reason: configured[flag] !== true ? "FEATURE_DISABLED" : dependency ? null : reason, checkedAt: new Date().toISOString(), implementationVersion: "agent_work_v1" });
    return { protocol: "agent_work_v1", skills: make("agent_work_skills_enabled", true, "LOCAL_CONTROL_PLANE_ONLY"), routines: make("agent_work_routines_enabled", hermes, "HERMES_ADAPTER_NOT_CONFIGURED"), goals: make("agent_work_goals_enabled", true, "LOCAL_CONTROL_PLANE_ONLY"), attention: make("agent_work_attention_enabled", true, "LOCAL_CONTROL_PLANE_ONLY"), memory: make("agent_work_memory_enabled", false, "CONTEXTHUB_ADAPTER_NOT_VERIFIED"), browser: make("agent_work_browser_enabled", false, "BROWSER_BROKER_NOT_VERIFIED"), teaching: make("agent_work_teaching_enabled", false, "BROWSER_BROKER_NOT_VERIFIED") };
  }

  listSkills(officeId?: string): Record<string, unknown>[] {
    const rows = officeId ? this.db.all<Row>("SELECT * FROM work_skills WHERE office_id = ? AND archived_at IS NULL ORDER BY updated_at DESC, id DESC", officeId) : this.db.all<Row>("SELECT * FROM work_skills WHERE archived_at IS NULL ORDER BY updated_at DESC, id DESC");
    return rows.map((row) => this.skillProjection(row));
  }

  getSkill(skillId: string): Record<string, unknown> | undefined {
    const row = this.db.one<Row>("SELECT * FROM work_skills WHERE id = ? AND archived_at IS NULL", skillId); if (!row) return undefined;
    return this.skillProjection(row, true);
  }

  getSkillVersion(skillId: string, version: number): Record<string, unknown> | undefined {
    const row = this.db.one<Row>("SELECT s.*, v.* FROM work_skills s JOIN work_skill_versions v ON v.skill_id = s.id AND v.version = ? WHERE s.id = ? AND s.archived_at IS NULL", version, skillId); if (!row) return undefined;
    return this.versionProjection(row);
  }

  createSkillDraft(input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> {
    this.requireFeature("agent_work_skills_enabled");
    rejectUnknown(input, ["office_id", "name", "bundle_artifact_id", "content_hash", "spec", "source_mission_id", "source_result_hash", "source_ref"], "request");
    const officeId = text(input.office_id, "office_id"); const name = text(input.name, "name", 200); const artifactId = text(input.bundle_artifact_id, "bundle_artifact_id"); const contentHash = text(input.content_hash, "content_hash", 100);
    const spec = object(input.spec, "spec"); this.validateSkillSpec(spec);
    const sourceMissionId = optionalText(input.source_mission_id, "source_mission_id");
    const request = { officeId, name, artifactId, contentHash, spec, sourceMissionId, sourceRef: input.source_ref ?? null };
    const requestHash = safeHash(request); const operation = this.startOperation("control.skills.draft_create", "SKILL", null, actorId, idempotencyKey, requestHash, request, now);
    if (operation.replayed) return operation.result;
    const skillId = uuidv7(now); const version = 1;
    try {
      this.db.transaction(() => {
        this.requireOffice(officeId); this.requireArtifact(artifactId, contentHash);
        if (sourceMissionId && !this.db.one("SELECT id FROM missions WHERE id = ? AND archived_at IS NULL", sourceMissionId)) throw new Error("MISSION_NOT_FOUND");
        this.db.run("INSERT INTO work_skills(id, office_id, name, next_version, created_at, updated_at) VALUES (?, ?, ?, 2, ?, ?)", skillId, officeId, name, now, now);
        this.db.run("INSERT INTO work_skill_versions(skill_id, version, artifact_id, content_hash, spec_json, source_mission_id, source_result_hash, validation_state, compatibility_state, lifecycle, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'DRAFT', ?, 'CANDIDATE', ?)", skillId, version, artifactId, contentHash, JSON.stringify(spec), sourceMissionId, optionalText(input.source_result_hash, "source_result_hash", 100), this.compatibility(spec), now);
        this.pinArtifact("SKILL_VERSION", `${skillId}:${version}`, version, artifactId, "BUNDLE", now);
        this.recordOperationApplied(operation.id, { skill_id: skillId, version, state: "DRAFT" }, now);
        this.appendEvent("SKILL", skillId, 1, "skill.created", { skill_id: skillId, version }, now);
      });
    } catch (error) { this.recordOperationError(operation.id, error, now); throw error; }
    this.events.publish({ type: "agent-work.skill.updated", skillId, version });
    return this.operationResult(operation.id);
  }

  createSkillVersion(skillId: string, input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> {
    this.requireFeature("agent_work_skills_enabled");
    rejectUnknown(input, ["expected_revision", "bundle_artifact_id", "content_hash", "spec", "source_mission_id", "source_result_hash"], "request");
    const artifactId = text(input.bundle_artifact_id, "bundle_artifact_id"); const contentHash = text(input.content_hash, "content_hash", 100); const spec = object(input.spec, "spec"); this.validateSkillSpec(spec);
    const expectedRevision = boundedInt(input.expected_revision, "expected_revision", -1, Number.MAX_SAFE_INTEGER); if (expectedRevision < 0) throw new Error("REVISION_REQUIRED");
    const request = { skillId, artifactId, contentHash, spec, expectedRevision }; const requestHash = safeHash(request); const operation = this.startOperation("control.skills.version_create", "SKILL", skillId, actorId, idempotencyKey, requestHash, request, now); if (operation.replayed) return operation.result;
    let version = 0;
    try {
      this.db.transaction(() => {
        const skill = this.db.one<Row>("SELECT * FROM work_skills WHERE id = ? AND archived_at IS NULL", skillId); if (!skill) throw new Error("SKILL_NOT_FOUND"); if (Number(skill.revision) !== expectedRevision) throw new Error("REVISION_CONFLICT");
        this.requireArtifact(artifactId, contentHash); version = Number(skill.next_version); this.db.run("INSERT INTO work_skill_versions(skill_id, version, artifact_id, content_hash, spec_json, source_mission_id, source_result_hash, validation_state, compatibility_state, lifecycle, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'DRAFT', ?, 'CANDIDATE', ?)", skillId, version, artifactId, contentHash, JSON.stringify(spec), optionalText(input.source_mission_id, "source_mission_id"), optionalText(input.source_result_hash, "source_result_hash", 100), this.compatibility(spec), now); this.db.run("UPDATE work_skills SET next_version = next_version + 1, revision = revision + 1, updated_at = ? WHERE id = ?", now, skillId); this.pinArtifact("SKILL_VERSION", `${skillId}:${version}`, version, artifactId, "BUNDLE", now); this.recordOperationApplied(operation.id, { skill_id: skillId, version, state: "DRAFT", revision: expectedRevision + 1 }, now); this.appendEvent("SKILL", skillId, expectedRevision + 1, "skill.version_created", { skill_id: skillId, version }, now);
      });
    } catch (error) { this.recordOperationError(operation.id, error, now); throw error; }
    return this.operationResult(operation.id);
  }

  validateSkill(skillId: string, version: number, input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> {
    this.requireFeature("agent_work_skills_enabled");
    rejectUnknown(input, ["mode", "case_manifest", "test_inputs"], "request");
    const mode = text(input.mode, "mode", 30); if (!["VALIDATE_ONLY", "SANDBOX_RUN", "LIVE_RUN"].includes(mode)) throw new Error("INVALID_FIELD:mode");
    const manifest = Array.isArray(input.case_manifest) ? input.case_manifest : ["normal", "missing_source", "schema_changed"];
    const cases = [...new Set(manifest.map((value) => text(value, "case_manifest", 80)))]; for (const key of ["normal", "missing_source", "schema_changed"]) if (!cases.includes(key)) throw new Error("INVALID_FIELD:case_manifest");
    const request = { skillId, version, mode, cases, input_hash: safeHash(input.test_inputs ?? {}) }; const requestHash = safeHash(request); const operation = this.startOperation("control.skills.validate", "SKILL_VERSION", `${skillId}:${version}`, actorId, idempotencyKey, requestHash, request, now); if (operation.replayed) return operation.result;
    try {
      this.db.transaction(() => {
        const row = this.db.one<Row>("SELECT * FROM work_skill_versions WHERE skill_id = ? AND version = ?", skillId, version); if (!row) throw new Error("SKILL_VERSION_NOT_FOUND");
        if (mode !== "VALIDATE_ONLY" && (this.capabilities().skills as Row).available !== true) throw new Error("CAPABILITY_UNAVAILABLE");
        this.db.run("UPDATE work_skill_versions SET validation_state = 'VALIDATING', state_revision = state_revision + 1 WHERE skill_id = ? AND version = ?", skillId, version);
        for (const caseKey of cases) {
          const state = mode === "VALIDATE_ONLY" ? "PASSED" : "UNAVAILABLE";
          const evidence = { mode, case_key: caseKey, checks: { schema: "PASSED", capabilities: "PASSED", effects: mode === "VALIDATE_ONLY" ? "NOT_EXECUTED" : "UNAVAILABLE" }, note: mode === "VALIDATE_ONLY" ? "Static validation only; this cannot activate a skill." : "Executor capability is not connected." };
          this.db.run("INSERT INTO skill_validation_runs(id, skill_id, skill_version, case_key, mode, input_hash, operation_id, evidence_json, state, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", uuidv7(now), skillId, version, caseKey, mode, safeHash(input.test_inputs ?? {}), operation.id, JSON.stringify(evidence), state, now);
        }
        const finalState = mode === "VALIDATE_ONLY" ? "PASSED" : "FAILED"; this.db.run("UPDATE work_skill_versions SET validation_state = ?, state_revision = state_revision + 1 WHERE skill_id = ? AND version = ?", finalState, skillId, version); this.recordOperationApplied(operation.id, { skill_id: skillId, version, mode, validation_state: finalState, cases }, now); this.appendEvent("SKILL_VERSION", `${skillId}:${version}`, Number(row.state_revision) + 2, "skill.validation.completed", { skill_id: skillId, version, mode, state: finalState }, now);
      });
    } catch (error) { this.recordOperationError(operation.id, error, now); throw error; }
    return this.operationResult(operation.id);
  }

  activateSkill(skillId: string, input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> {
    rejectUnknown(input, ["version", "expected_revision", "expected_state_revision"], "request");
    this.requireFeature("agent_work_skills_enabled"); const version = boundedInt(input.version, "version", -1, 10_000); if (version < 1) throw new Error("INVALID_FIELD:version"); const expectedRevision = boundedInt(input.expected_revision, "expected_revision", -1, Number.MAX_SAFE_INTEGER); if (expectedRevision < 0) throw new Error("REVISION_REQUIRED"); const expectedStateRevision = boundedInt(input.expected_state_revision, "expected_state_revision", -1, Number.MAX_SAFE_INTEGER); if (expectedStateRevision < 0) throw new Error("REVISION_REQUIRED");
    const request = { skillId, version, expectedRevision, expectedStateRevision }; const requestHash = safeHash(request); const operation = this.startOperation("control.skills.activate", "SKILL", skillId, actorId, idempotencyKey, requestHash, request, now); if (operation.replayed) return operation.result;
    try {
      this.db.transaction(() => {
        const skill = this.db.one<Row>("SELECT * FROM work_skills WHERE id = ? AND archived_at IS NULL", skillId); const row = this.db.one<Row>("SELECT * FROM work_skill_versions WHERE skill_id = ? AND version = ?", skillId, version); if (!skill) throw new Error("SKILL_NOT_FOUND"); if (!row) throw new Error("SKILL_VERSION_NOT_FOUND"); if (Number(skill.revision) !== expectedRevision) throw new Error("REVISION_CONFLICT"); if (Number(row.state_revision) !== expectedStateRevision) throw new Error("REVISION_CONFLICT"); if (row.validation_state !== "PASSED" || row.compatibility_state !== "COMPATIBLE" || row.lifecycle !== "CANDIDATE") throw new Error("VALIDATION_INCOMPLETE"); const required = ["normal", "missing_source", "schema_changed"]; const validated = this.db.all<Row>("SELECT case_key FROM skill_validation_runs WHERE skill_id = ? AND skill_version = ? AND state = 'PASSED' GROUP BY case_key", skillId, version).map((item) => String(item.case_key)); if (required.some((key) => !validated.includes(key)) || !this.db.one("SELECT 1 FROM skill_validation_runs WHERE skill_id = ? AND skill_version = ? AND mode <> 'VALIDATE_ONLY' AND state = 'PASSED'", skillId, version)) throw new Error("VALIDATION_INCOMPLETE");
        if (skill.active_version && Number(skill.active_version) !== version) this.db.run("UPDATE work_skill_versions SET lifecycle = 'DEPRECATED', state_revision = state_revision + 1 WHERE skill_id = ? AND version = ? AND lifecycle = 'READY'", skillId, skill.active_version);
        this.db.run("UPDATE work_skill_versions SET lifecycle = 'READY', state_revision = state_revision + 1 WHERE skill_id = ? AND version = ?", skillId, version); this.db.run("UPDATE work_skills SET active_version = ?, revision = revision + 1, updated_at = ? WHERE id = ?", version, now, skillId); this.recordOperationApplied(operation.id, { skill_id: skillId, version, lifecycle: "READY", revision: expectedRevision + 1 }, now); this.appendEvent("SKILL", skillId, expectedRevision + 1, "skill.activated", { skill_id: skillId, version }, now);
      });
    } catch (error) { this.recordOperationError(operation.id, error, now); throw error; }
    return this.operationResult(operation.id);
  }

  runSkill(skillId: string, input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> {
    rejectUnknown(input, ["version", "parameters", "mission_spec"], "request");
    this.requireFeature("agent_work_skills_enabled"); const version = boundedInt(input.version, "version", 0, 10_000); const parameters = object(input.parameters ?? {}, "parameters"); const row = this.db.one<Row>("SELECT s.*, v.content_hash, v.lifecycle, v.version FROM work_skills s JOIN work_skill_versions v ON v.skill_id = s.id AND v.version = COALESCE(?, s.active_version) WHERE s.id = ? AND s.archived_at IS NULL", version || null, skillId); if (!row) throw new Error("SKILL_NOT_FOUND"); if (row.lifecycle !== "READY") throw new Error("SKILL_NOT_READY"); if (!this.missions) throw new Error("MISSION_UNAVAILABLE");
    const request = { skillId, version: Number(row.version), parameters, missionSpec: input.mission_spec ?? null }; const requestHash = safeHash(request); const operation = this.startOperation("control.skills.run", "SKILL", skillId, actorId, idempotencyKey, requestHash, request, now); if (operation.replayed) return operation.result;
    try {
      const spec = parseJson(this.db.one<Row>("SELECT spec_json FROM work_skill_versions WHERE skill_id = ? AND version = ?", skillId, row.version)?.spec_json, {}); const missionSpec = object(input.mission_spec ?? {}, "mission_spec"); const missionInput: any = { officeId: String(row.office_id), title: String(missionSpec.title ?? row.name), goal: String(missionSpec.goal ?? spec.purpose ?? row.name), sourceRef: { kind: "SKILL", id: skillId, title: String(row.name) }, sourceIntentKey: `skill-run:${operation.id}`, scope: object(missionSpec.scope ?? {}, "mission_spec.scope"), limits: missionSpec.limits, delivery: missionSpec.delivery, inputs: [], brainProtocolVersion: Number(missionSpec.brain_protocol_version ?? 1), conversationRef: optionalText(missionSpec.conversation_ref, "mission_spec.conversation_ref") };
      const mission = this.missions.create(missionInput, `agent-work:${operation.id}`, now);
      this.db.transaction(() => { const runId = String(mission.response.missionRunId); this.db.run("INSERT INTO mission_skill_bindings(mission_run_id, skill_id, skill_version, content_hash, parameters_json, capability_snapshot_hash) VALUES (?, ?, ?, ?, ?, ?)", runId, skillId, Number(row.version), row.content_hash, JSON.stringify(parameters), safeHash(this.capabilities())); this.recordOperationApplied(operation.id, { mission_id: mission.response.missionId, mission_run_id: runId, skill_id: skillId, skill_version: Number(row.version), content_hash: row.content_hash }, now); this.appendEvent("SKILL", skillId, Number(row.revision), "skill.run.admitted", { operation_id: operation.id, mission_id: mission.response.missionId, mission_run_id: runId }, now); });
    } catch (error) { this.recordOperationError(operation.id, error, now); throw error; }
    return this.operationResult(operation.id);
  }

  listRoutines(officeId?: string): Record<string, unknown>[] { const rows = officeId ? this.db.all<Row>("SELECT * FROM routine_bindings WHERE office_id = ? ORDER BY updated_at DESC", officeId) : this.db.all<Row>("SELECT * FROM routine_bindings ORDER BY updated_at DESC"); return rows.map((row) => this.routineProjection(row)); }
  getRoutine(id: string): Record<string, unknown> | undefined { const row = this.db.one<Row>("SELECT * FROM routine_bindings WHERE id = ?", id); return row ? this.routineProjection(row, true) : undefined; }

  createRoutine(input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> {
    rejectUnknown(input, ["office_id", "skill_id", "skill_version", "trigger_intent", "scope_ref", "conversation_ref", "policy_ref"], "request");
    this.requireFeature("agent_work_routines_enabled"); const officeId = text(input.office_id, "office_id"); const skillId = text(input.skill_id, "skill_id"); const skillVersion = boundedInt(input.skill_version, "skill_version", 0, 10_000); const trigger = object(input.trigger_intent, "trigger_intent"); const request = { officeId, skillId, skillVersion, trigger, scopeRef: input.scope_ref ?? null, conversationRef: input.conversation_ref ?? null, policyRef: input.policy_ref ?? null }; const requestHash = safeHash(request); const operation = this.startOperation("control.routines.create", "ROUTINE_BINDING", null, actorId, idempotencyKey, requestHash, request, now); if (operation.replayed) return operation.result;
    const id = uuidv7(now); const nativeKey = `cp-binding:${id}`;
    try {
      this.db.transaction(() => { this.requireOffice(officeId); const skill = this.db.one<Row>("SELECT * FROM work_skill_versions WHERE skill_id = ? AND version = ? AND lifecycle = 'READY'", skillId, skillVersion || Number(this.db.one<Row>("SELECT active_version FROM work_skills WHERE id = ?", skillId)?.active_version ?? 0)); if (!skill) throw new Error("SKILL_NOT_READY"); this.db.run("INSERT INTO routine_bindings(id, office_id, native_key, desired_revision, remote_state, sync_state, admission_blocked, observed_at, created_at, updated_at) VALUES (?, ?, ?, 1, 'UNKNOWN', 'PENDING', 1, ?, ?, ?)", id, officeId, nativeKey, now, now, now); this.db.run("INSERT INTO routine_binding_revisions(binding_id, revision, skill_id, skill_version, intent_json, request_hash, operation_id, created_at) VALUES (?, 1, ?, ?, ?, ?, ?, ?)", id, skillId, skillVersion || skill.version, JSON.stringify(request), requestHash, operation.id, now); this.createCommand(operation.id, "HERMES", "routine.configure", `routine:${id}:1`, { native_key: nativeKey, binding_id: id, binding_revision: 1, desired_state: "ACTIVE", intent: request }, requestHash, now); this.recordOperationApplied(operation.id, { binding_id: id, native_key: nativeKey, sync_state: "PENDING", admission_blocked: true }, now); this.appendEvent("ROUTINE_BINDING", id, 1, "routine.created", { binding_id: id, native_key: nativeKey }, now); });
    } catch (error) { this.recordOperationError(operation.id, error, now); throw error; }
    this.events.publish({ type: "agent-work.routine.updated", bindingId: id }); return this.operationResult(operation.id);
  }

  applyRoutineReceipt(input: JsonObject, now = Date.now()): Record<string, unknown> {
    const bindingId = text(input.binding_id, "binding_id"); const binding = this.db.one<Row>("SELECT * FROM routine_bindings WHERE id = ?", bindingId); if (!binding) throw new Error("ROUTINE_NOT_FOUND"); const revision = boundedInt(input.binding_revision, "binding_revision", -1, Number.MAX_SAFE_INTEGER); if (revision < 1) throw new Error("INVALID_FIELD:binding_revision"); const processing = text(input.processing_state, "processing_state", 30); if (!["APPLIED", "REJECTED", "UNKNOWN"].includes(processing)) throw new Error("INVALID_FIELD:processing_state");
    this.db.transaction(() => { const desired = Number(binding.desired_revision); if (revision !== desired) { this.appendEvent("ROUTINE_BINDING", bindingId, desired, "routine.receipt.stale", { binding_id: bindingId, binding_revision: revision }, now); return; } const effective = processing === "APPLIED" ? 0 : 1; this.db.run("UPDATE routine_bindings SET routine_id = ?, effective_revision = ?, native_revision = ?, remote_state = ?, sync_state = ?, admission_blocked = ?, next_fire_at = ?, observed_at = ?, updated_at = ? WHERE id = ?", optionalText(input.routine_id, "routine_id"), processing === "APPLIED" ? revision : null, input.native_revision === undefined ? null : boundedInt(input.native_revision, "native_revision", 0, Number.MAX_SAFE_INTEGER), String(input.remote_state ?? "UNKNOWN"), processing === "APPLIED" ? "EFFECTIVE" : processing, effective, input.next_fire_at === undefined ? null : boundedInt(input.next_fire_at, "next_fire_at", 0, Number.MAX_SAFE_INTEGER), now, now, bindingId); this.appendEvent("ROUTINE_BINDING", bindingId, revision, "routine.receipt.applied", { binding_id: bindingId, processing_state: processing }, now); });
    return this.getRoutine(bindingId)!;
  }

  receiveOccurrence(input: JsonObject, actorId: string, now = Date.now()): Record<string, unknown> {
    rejectUnknown(input, ["binding_id", "source_occurrence_key", "binding_revision", "native_revision", "payload", "scheduled_for_utc", "mission"], "request");
    this.requireFeature("agent_work_routines_enabled"); const bindingId = text(input.binding_id, "binding_id"); const sourceKey = text(input.source_occurrence_key, "source_occurrence_key", 500); const bindingRevision = boundedInt(input.binding_revision, "binding_revision", -1, Number.MAX_SAFE_INTEGER); const nativeRevision = boundedInt(input.native_revision, "native_revision", -1, Number.MAX_SAFE_INTEGER); if (bindingRevision < 1 || nativeRevision < 1) throw new Error("INVALID_FIELD:revision"); const payload = object(input.payload ?? {}, "payload"); const payloadHash = safeHash(payload); const existing = this.db.one<Row>("SELECT * FROM routine_occurrences WHERE source_key = ?", sourceKey); if (existing) { if (existing.payload_hash !== payloadHash) throw new Error("IDEMPOTENCY_CONFLICT"); return this.occurrenceProjection(existing); }
    const binding = this.db.one<Row>("SELECT * FROM routine_bindings WHERE id = ?", bindingId); if (!binding) throw new Error("ROUTINE_NOT_FOUND"); if (Number(binding.effective_revision) !== bindingRevision || Number(binding.native_revision) !== nativeRevision || Number(binding.admission_blocked) === 1) { this.db.run("INSERT INTO routine_occurrences(source_key, binding_id, binding_revision, native_revision, payload_hash, payload_json, scheduled_for, state, reason_code, received_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'REJECTED', ?, ?, ?)", sourceKey, bindingId, bindingRevision, nativeRevision, payloadHash, JSON.stringify(payload), input.scheduled_for_utc ? Date.parse(String(input.scheduled_for_utc)) : null, "BINDING_REVISION_STALE", now, now); throw new Error("BINDING_REVISION_STALE"); }
    const missionInput: any = object(input.mission, "mission"); const missionKey = `routine-occurrence:${sourceKey}`; let mission: any;
    if (!this.missions) throw new Error("MISSION_UNAVAILABLE");
    try { const scope = object(missionInput.scope ?? {}, "mission.scope"); const missionScope = { workspaceIds: Array.isArray(scope.workspace_ids) ? scope.workspace_ids.map(String) : [], capabilities: Array.isArray(scope.capabilities) ? scope.capabilities.map(String) : [], externalEffects: Array.isArray(scope.external_effects) ? scope.external_effects.map(String) : [] }; mission = this.missions.create({ officeId: String(binding.office_id), title: String(missionInput.title ?? "例行工作"), goal: String(missionInput.goal ?? "執行例行工作"), sourceRef: { kind: "ROUTINE_OCCURRENCE", id: sourceKey }, sourceIntentKey: missionKey, conversationRef: optionalText(missionInput.conversation_ref, "mission.conversation_ref"), scope: missionScope, limits: missionInput.limits, delivery: missionInput.delivery, inputs: [], brainProtocolVersion: Number(missionInput.brain_protocol_version ?? 1) as 1 | 2 }, `routine:${sourceKey}`, now); } catch (error) { this.db.run("INSERT INTO routine_occurrences(source_key, binding_id, binding_revision, native_revision, payload_hash, payload_json, scheduled_for, state, reason_code, received_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'REJECTED', ?, ?, ?)", sourceKey, bindingId, bindingRevision, nativeRevision, payloadHash, JSON.stringify(payload), input.scheduled_for_utc ? Date.parse(String(input.scheduled_for_utc)) : null, "MISSION_ADMISSION_FAILED", now, now); throw error; }
    this.db.transaction(() => { this.db.run("INSERT INTO routine_occurrences(source_key, binding_id, binding_revision, native_revision, payload_hash, payload_json, scheduled_for, state, mission_id, received_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'ADMITTED', ?, ?, ?)", sourceKey, bindingId, bindingRevision, nativeRevision, payloadHash, JSON.stringify(payload), input.scheduled_for_utc ? Date.parse(String(input.scheduled_for_utc)) : null, String(mission.response.missionId), now, now); this.appendEvent("ROUTINE_BINDING", bindingId, bindingRevision, "routine.occurrence.admitted", { source_key: sourceKey, mission_id: mission.response.missionId }, now); });
    return { source_key: sourceKey, state: "ADMITTED", mission_id: mission.response.missionId, replayed: Boolean(mission.replayed) };
  }

  listGoals(officeId?: string): Record<string, unknown>[] { const rows = officeId ? this.db.all<Row>("SELECT * FROM goals WHERE office_id = ? ORDER BY updated_at DESC", officeId) : this.db.all<Row>("SELECT * FROM goals ORDER BY updated_at DESC"); return rows.map((row) => this.goalProjection(row)); }
  getGoal(id: string): Record<string, unknown> | undefined { const row = this.db.one<Row>("SELECT * FROM goals WHERE id = ?", id); return row ? this.goalProjection(row, true) : undefined; }

  createGoal(input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> {
    rejectUnknown(input, ["office_id", "title", "objective", "scope", "limits", "milestones", "deadline_at", "next_review_at"], "request");
    this.requireFeature("agent_work_goals_enabled"); const officeId = text(input.office_id, "office_id"); const title = text(input.title, "title", 500); const objective = object(input.objective, "objective"); const scope = object(input.scope ?? {}, "scope"); const limits = object(input.limits ?? {}, "limits"); const milestoneInput = Array.isArray(input.milestones) ? input.milestones : []; if (milestoneInput.length > 50) throw new Error("INVALID_FIELD:milestones"); const request = { officeId, title, objective, scope, limits, milestones: milestoneInput }; const requestHash = safeHash(request); const operation = this.startOperation("control.goals.create", "GOAL", null, actorId, idempotencyKey, requestHash, request, now); if (operation.replayed) return operation.result; const goalId = uuidv7(now);
    try {
      this.db.transaction(() => { this.requireOffice(officeId); this.db.run("INSERT INTO goals(id, office_id, title, objective_json, scope_json, limits_json, state, health, deadline_at, next_review_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 'DRAFT', 'ON_TRACK', ?, ?, ?, ?)", goalId, officeId, title, JSON.stringify(objective), JSON.stringify(scope), JSON.stringify(limits), input.deadline_at === undefined ? null : boundedInt(input.deadline_at, "deadline_at", 0, Number.MAX_SAFE_INTEGER), input.next_review_at === undefined ? null : boundedInt(input.next_review_at, "next_review_at", 0, Number.MAX_SAFE_INTEGER), now, now); milestoneInput.forEach((raw, index) => { const item = object(raw, `milestones[${index}]`); this.db.run("INSERT INTO goal_milestones(id, goal_id, ordinal, title, required, criteria_json, state, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 'OPEN', ?, ?)", uuidv7(now + index + 1), goalId, index + 1, text(item.title, `milestones[${index}].title`, 500), item.required === false ? 0 : 1, JSON.stringify(object(item.criteria ?? {}, `milestones[${index}].criteria`)), now, now); }); const dimensions = limits.dimensions && typeof limits.dimensions === "object" && !Array.isArray(limits.dimensions) ? limits.dimensions as Row : {}; const periodKey = typeof limits.budget_period === "string" ? limits.budget_period : "lifetime"; for (const [dimension, rawLimit] of Object.entries(dimensions)) { const limit = boundedInt(rawLimit, `limits.dimensions.${dimension}`, -1, Number.MAX_SAFE_INTEGER); if (limit < 0) throw new Error(`INVALID_FIELD:limits.dimensions.${dimension}`); this.db.run("INSERT INTO goal_budget_accounts(goal_id, period_key, dimension, limit_amount, state, period_start) VALUES (?, ?, ?, ?, 'OPEN', ?)", goalId, periodKey, dimension, limit, now); } this.recordOperationApplied(operation.id, { goal_id: goalId, state: "DRAFT", revision: 1 }, now); this.appendEvent("GOAL", goalId, 1, "goal.created", { goal_id: goalId }, now); });
    } catch (error) { this.recordOperationError(operation.id, error, now); throw error; }
    return this.operationResult(operation.id);
  }

  goalCommand(goalId: string, input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> {
    rejectUnknown(input, ["kind", "expected_revision", "payload"], "request");
    const kind = text(input.kind, "kind", 40); const expectedRevision = boundedInt(input.expected_revision, "expected_revision", -1, Number.MAX_SAFE_INTEGER); if (expectedRevision < 1) throw new Error("REVISION_REQUIRED"); const request = { goalId, kind, expectedRevision, payload: input.payload ?? null }; const requestHash = safeHash(request); const operation = this.startOperation("control.goals.command", "GOAL", goalId, actorId, idempotencyKey, requestHash, request, now); if (operation.replayed) return operation.result;
    const allowed = ["ACTIVATE", "REVISE", "PAUSE", "RESUME", "CANCEL", "ARCHIVE", "ACCEPT_MILESTONE", "MARK_ACHIEVED"]; if (!allowed.includes(kind)) throw new Error("INVALID_FIELD:kind");
    try {
      this.db.transaction(() => {
        const goal = this.db.one<Row>("SELECT * FROM goals WHERE id = ?", goalId); if (!goal) throw new Error("GOAL_NOT_FOUND"); if (Number(goal.revision) !== expectedRevision) throw new Error("REVISION_CONFLICT");
        const state: Record<string, string> = { ACTIVATE: "ACTIVE", PAUSE: "PAUSED", RESUME: "ACTIVE", CANCEL: "CANCELLED", ARCHIVE: "ARCHIVED", MARK_ACHIEVED: "ACHIEVED" }; const next = state[kind];
        if (kind === "ACCEPT_MILESTONE") {
          const payload = object(input.payload, "payload"); const milestoneId = text(payload.milestone_id, "payload.milestone_id"); const milestone = this.db.one<Row>("SELECT * FROM goal_milestones WHERE id = ? AND goal_id = ?", milestoneId, goalId); if (!milestone) throw new Error("MILESTONE_NOT_FOUND");
          this.db.run("UPDATE goal_milestones SET state = 'ACCEPTED', acceptance_json = ?, revision = revision + 1, updated_at = ? WHERE id = ?", JSON.stringify(payload.acceptance ?? {}), now, milestoneId);
        } else if (kind === "REVISE") {
          const payload = object(input.payload, "payload"); const objective = payload.objective === undefined ? parseJson(goal.objective_json) : object(payload.objective, "payload.objective"); const scope = payload.scope === undefined ? parseJson(goal.scope_json) : object(payload.scope, "payload.scope"); const limits = payload.limits === undefined ? parseJson(goal.limits_json) : object(payload.limits, "payload.limits");
          this.db.run("UPDATE goals SET title = COALESCE(?, title), objective_json = ?, scope_json = ?, limits_json = ?, revision = revision + 1, projection_revision = projection_revision + 1, updated_at = ? WHERE id = ?", payload.title === undefined ? null : text(payload.title, "payload.title", 500), JSON.stringify(objective), JSON.stringify(scope), JSON.stringify(limits), now, goalId);
        } else {
          if (kind === "ACTIVATE" && goal.state !== "DRAFT") throw new Error("INVALID_GOAL_STATE"); if (kind === "MARK_ACHIEVED" && this.db.one("SELECT 1 FROM goal_milestones WHERE goal_id = ? AND required = 1 AND state <> 'ACCEPTED' LIMIT 1", goalId)) throw new Error("MILESTONES_INCOMPLETE");
          if (next) this.db.run("UPDATE goals SET state = ?, revision = revision + 1, projection_revision = projection_revision + 1, updated_at = ? WHERE id = ?", next, now, goalId);
        }
        this.recordOperationApplied(operation.id, { goal_id: goalId, kind, state: kind === "ACCEPT_MILESTONE" || kind === "REVISE" ? goal.state : next, revision: Number(goal.revision) + 1 }, now); this.appendEvent("GOAL", goalId, Number(goal.revision) + 1, `goal.${kind.toLowerCase()}`, { goal_id: goalId, kind }, now);
      });
    } catch (error) { this.recordOperationError(operation.id, error, now); throw error; }
    return this.operationResult(operation.id);
  }

  reserveBudget(goalId: string, input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> {
    rejectUnknown(input, ["period_key", "dimension", "amount", "mission_run_id"], "request");
    const periodKey = text(input.period_key, "period_key", 100); const dimension = text(input.dimension, "dimension", 100); const amount = boundedInt(input.amount, "amount", -1, Number.MAX_SAFE_INTEGER); if (amount < 0) throw new Error("INVALID_FIELD:amount"); const missionRunId = optionalText(input.mission_run_id, "mission_run_id"); const request = { goalId, periodKey, dimension, amount, missionRunId }; const requestHash = safeHash(request); const operation = this.startOperation("control.goals.budget_reserve", "GOAL", goalId, actorId, idempotencyKey, requestHash, request, now); if (operation.replayed) return operation.result; const reservationId = uuidv7(now);
    try { this.db.transaction(() => { const account = this.db.one<Row>("SELECT * FROM goal_budget_accounts WHERE goal_id = ? AND period_key = ? AND dimension = ?", goalId, periodKey, dimension); if (!account) throw new Error("BUDGET_ACCOUNT_NOT_FOUND"); if (Number(account.limit_amount) - Number(account.consumed) - Number(account.reserved) < amount) throw new Error("BUDGET_EXHAUSTED"); this.db.run("INSERT INTO goal_budget_reservations(id, goal_id, period_key, dimension, mission_run_id, operation_id, remaining, state, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'RESERVED', ?, ?)", reservationId, goalId, periodKey, dimension, missionRunId, missionRunId ? null : operation.id, amount, now, now); this.db.run("UPDATE goal_budget_accounts SET reserved = reserved + ? WHERE goal_id = ? AND period_key = ? AND dimension = ?", amount, goalId, periodKey, dimension); this.recordOperationApplied(operation.id, { reservation_id: reservationId, amount, state: "RESERVED" }, now); this.appendEvent("GOAL", goalId, 1, "goal.budget.reserved", { reservation_id: reservationId, amount, dimension }, now); }); } catch (error) { this.recordOperationError(operation.id, error, now); throw error; }
    return this.operationResult(operation.id);
  }

  chargeBudget(reservationId: string, chargeKey: string, amount: number, evidence: JsonObject, now = Date.now()): Record<string, unknown> { if (!Number.isInteger(amount) || amount < 0) throw new Error("INVALID_FIELD:amount"); let result!: Record<string, unknown>; this.db.transaction(() => { const reservation = this.db.one<Row>("SELECT * FROM goal_budget_reservations WHERE id = ?", reservationId); if (!reservation) throw new Error("BUDGET_RESERVATION_NOT_FOUND"); const existing = this.db.one<Row>("SELECT * FROM goal_budget_entries WHERE reservation_id = ? AND charge_key = ?", reservationId, chargeKey); if (existing) { result = { reservation_id: reservationId, charge_key: chargeKey, amount: Number(existing.amount), replayed: true }; return; } if (Number(reservation.remaining) < amount) throw new Error("BUDGET_EXHAUSTED"); this.db.run("INSERT INTO goal_budget_entries(id, reservation_id, charge_key, amount, evidence_json, created_at) VALUES (?, ?, ?, ?, ?, ?)", uuidv7(now), reservationId, chargeKey, amount, JSON.stringify(evidence), now); const remaining = Number(reservation.remaining) - amount; this.db.run("UPDATE goal_budget_reservations SET remaining = ?, state = ?, updated_at = ? WHERE id = ?", remaining, remaining === 0 ? "CHARGED" : "RESERVED", now, reservationId); this.db.run("UPDATE goal_budget_accounts SET reserved = reserved - ?, consumed = consumed + ? WHERE goal_id = ? AND period_key = ? AND dimension = ?", amount, amount, reservation.goal_id, reservation.period_key, reservation.dimension); result = { reservation_id: reservationId, charge_key: chargeKey, amount, remaining, replayed: false }; }); return result; }

  listAttention(filters: { state?: string; severity?: string; limit?: number } = {}): Record<string, unknown>[] { const conditions: string[] = ["1=1"]; const params: unknown[] = []; if (filters.state) { conditions.push("state = ?"); params.push(filters.state); } if (filters.severity) { conditions.push("severity = ?"); params.push(filters.severity); } const limit = Math.min(100, Math.max(1, filters.limit ?? 50)); return this.db.all<Row>(`SELECT * FROM attention_items WHERE ${conditions.join(" AND ")} ORDER BY CASE severity WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END, updated_at DESC LIMIT ?`, ...params, limit).map((row) => this.attentionProjection(row)); }
  upsertAttention(input: JsonObject, now = Date.now()): Record<string, unknown> { const subjectKind = text(input.subject_kind, "subject_kind"); const subjectId = text(input.subject_id, "subject_id"); const reasonCode = text(input.reason_code, "reason_code"); const fingerprint = text(input.fingerprint, "fingerprint", 200); const severity = String(input.severity ?? "NORMAL"); if (!["LOW", "NORMAL", "HIGH", "CRITICAL"].includes(severity)) throw new Error("INVALID_FIELD:severity"); const evidence = object(input.evidence ?? {}, "evidence"); let row!: Row; this.db.transaction(() => { const existing = this.db.one<Row>("SELECT * FROM attention_items WHERE subject_kind = ? AND subject_id = ? AND reason_code = ? AND state IN ('OPEN', 'SNOOZED') ORDER BY episode DESC LIMIT 1", subjectKind, subjectId, reasonCode); if (existing && existing.fingerprint === fingerprint) { row = existing; return; } const episode = Number(existing?.episode ?? 0) + 1; const id = uuidv7(now); if (existing) this.db.run("UPDATE attention_items SET state = 'SUPERSEDED', revision = revision + 1, updated_at = ? WHERE id = ?", now, existing.id); this.db.run("INSERT INTO attention_items(id, subject_kind, subject_id, reason_code, episode, severity, state, fingerprint, evidence_json, action_ref_json, deadline_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 'OPEN', ?, ?, ?, ?, ?, ?)", id, subjectKind, subjectId, reasonCode, episode, severity, fingerprint, JSON.stringify(evidence), input.action_ref ? JSON.stringify(input.action_ref) : null, input.deadline_at === undefined ? null : boundedInt(input.deadline_at, "deadline_at", 0, Number.MAX_SAFE_INTEGER), now, now); row = this.db.one<Row>("SELECT * FROM attention_items WHERE id = ?", id)!; this.appendEvent("ATTENTION", id, 1, "attention.opened", { id, subject_kind: subjectKind, subject_id: subjectId, reason_code: reasonCode }, now); }); this.events.publish({ type: "agent-work.attention.updated", attentionId: row.id }); return this.attentionProjection(row); }
  attentionCommand(id: string, input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> { const kind = text(input.kind, "kind", 30); const row = this.db.one<Row>("SELECT * FROM attention_items WHERE id = ?", id); if (!row) throw new Error("ATTENTION_NOT_FOUND"); const expectedRevision = boundedInt(input.expected_revision, "expected_revision", -1, Number.MAX_SAFE_INTEGER); if (expectedRevision < 1) throw new Error("REVISION_REQUIRED"); const request = { id, kind, expectedRevision, payload: input.payload ?? null }; const requestHash = safeHash(request); const operation = this.startOperation("control.attention.command", "ATTENTION", id, actorId, idempotencyKey, requestHash, request, now); if (operation.replayed) return operation.result; try { this.db.transaction(() => { const current = this.db.one<Row>("SELECT * FROM attention_items WHERE id = ?", id)!; if (Number(current.revision) !== expectedRevision) throw new Error("REVISION_CONFLICT"); if (!["READ", "SNOOZE", "DISMISS_SUGGESTION"].includes(kind)) throw new Error("INVALID_FIELD:kind"); if (kind === "READ") this.db.run("UPDATE attention_items SET read_through_revision = MAX(read_through_revision, revision), updated_at = ? WHERE id = ?", now, id); else if (kind === "SNOOZE") this.db.run("UPDATE attention_items SET state = 'SNOOZED', snooze_until = ?, revision = revision + 1, updated_at = ? WHERE id = ?", boundedInt(object(input.payload, "payload").snooze_until, "payload.snooze_until", 0, Number.MAX_SAFE_INTEGER), now, id); else this.db.run("UPDATE attention_items SET state = 'SUPERSEDED', revision = revision + 1, updated_at = ? WHERE id = ?", now, id); this.recordOperationApplied(operation.id, { attention_id: id, kind, revision: kind === "READ" ? expectedRevision : expectedRevision + 1 }, now); this.appendEvent("ATTENTION", id, expectedRevision + (kind === "READ" ? 0 : 1), `attention.${kind.toLowerCase()}`, { id, kind }, now); }); } catch (error) { this.recordOperationError(operation.id, error, now); throw error; } return this.operationResult(operation.id); }
  memoryRequest(missionId: string, input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> { if (!this.db.one("SELECT id FROM missions WHERE id = ? AND archived_at IS NULL", missionId)) throw new Error("MISSION_NOT_FOUND"); if ((this.capabilities().memory as Row).available !== true) throw new Error("CONTEXT_UNAVAILABLE"); throw new Error("CONTEXT_UNAVAILABLE"); }

  artifactView(id: string): Record<string, unknown> { const row = this.db.one<Row>("SELECT * FROM artifacts WHERE id = ?", id); if (!row) throw new Error("ARTIFACT_NOT_FOUND"); const refs = this.db.all<Row>("SELECT owner_kind, owner_id, owner_version, purpose, metadata_json, pin_state, retain_until FROM agent_artifact_refs WHERE artifact_id = ? ORDER BY created_at", id).map((ref) => ({ ownerKind: ref.owner_kind, ownerId: ref.owner_id, ownerVersion: Number(ref.owner_version), purpose: ref.purpose, metadata: parseJson(ref.metadata_json), pinState: ref.pin_state, retainUntil: iso(ref.retain_until) })); const available = String(row.storage_state ?? "AVAILABLE") === "AVAILABLE" && this.artifacts.exists(String(row.storage_path)) && (() => { try { return ArtifactStorage.digest(this.artifacts.read(String(row.storage_path))) === String(row.sha256); } catch { return false; } })(); return { id: row.id, title: row.display_filename ?? row.filename, filename: row.display_filename ?? row.filename, mediaType: row.media_type, sizeBytes: Number(row.size_bytes), sha256: row.sha256, createdAt: iso(row.created_at), availability: available ? "AVAILABLE" : String(row.storage_state ?? "MISSING"), previewKind: row.preview_kind ?? null, downloadUrl: available ? `/api/v2/artifacts/${encodeURIComponent(id)}/download` : null, refs }; }

  listBrowserSessions(): Record<string, unknown>[] { return this.db.all<Row>("SELECT * FROM browser_sessions ORDER BY updated_at DESC").map((row) => this.browserProjection(row)); }
  getBrowserSession(id: string): Record<string, unknown> | undefined { const row = this.db.one<Row>("SELECT * FROM browser_sessions WHERE id = ?", id); return row ? this.browserProjection(row) : undefined; }
  createBrowserSession(input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> { this.requireFeature("agent_work_browser_enabled"); throw new Error("CAPABILITY_UNAVAILABLE"); }
  browserCommand(id: string, input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> { this.requireFeature("agent_work_browser_enabled"); const row = this.db.one<Row>("SELECT * FROM browser_sessions WHERE id = ?", id); if (!row) throw new Error("BROWSER_SESSION_NOT_FOUND"); const expectedRevision = boundedInt(input.expected_revision, "expected_revision", -1, Number.MAX_SAFE_INTEGER); const generation = boundedInt(input.generation, "generation", -1, Number.MAX_SAFE_INTEGER); if (expectedRevision < 1 || generation < 1) throw new Error("REVISION_REQUIRED"); if (Number(row.revision) !== expectedRevision || Number(row.generation) !== generation) throw new Error("REVISION_CONFLICT"); const kind = text(input.kind, "kind", 20); if (!["TAKEOVER", "RESUME", "STOP", "CLOSE"].includes(kind)) throw new Error("INVALID_FIELD:kind"); const request = { id, kind, expectedRevision, generation }; const operation = this.startOperation("control.browser.command", "BROWSER_SESSION", id, actorId, idempotencyKey, safeHash(request), request, now); if (operation.replayed) return operation.result; try { this.db.transaction(() => { const state = kind === "TAKEOVER" ? "TAKEOVER_PENDING" : kind === "RESUME" ? "LEASED" : kind === "CLOSE" ? "CLOSED" : "READY"; this.db.run("UPDATE browser_sessions SET state = ?, controller = ?, generation = generation + ?, revision = revision + 1, updated_at = ? WHERE id = ?", state, kind === "TAKEOVER" ? "OWNER" : kind === "RESUME" ? "AGENT" : "NONE", kind === "TAKEOVER" || kind === "RESUME" ? 1 : 0, now, id); this.recordOperationApplied(operation.id, { browser_session_id: id, state, generation: Number(row.generation) + (kind === "TAKEOVER" || kind === "RESUME" ? 1 : 0), revision: Number(row.revision) + 1 }, now); }); } catch (error) { this.recordOperationError(operation.id, error, now); throw error; } return this.operationResult(operation.id); }

  listTeachingSessions(): Record<string, unknown>[] { return this.db.all<Row>("SELECT * FROM teaching_sessions ORDER BY created_at DESC").map((row) => ({ id: row.id, browserSessionId: row.browser_session_id, revision: Number(row.revision), state: row.state, allowedOrigins: parseJson(row.allowed_origins_json, []), expiresAt: iso(row.expires_at), manifestArtifactId: row.manifest_artifact_id ?? null, draftSkillId: row.draft_skill_id ?? null })); }
  createTeachingSession(input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> { this.requireFeature("agent_work_teaching_enabled"); throw new Error("CAPABILITY_UNAVAILABLE"); }
  teachingCommand(id: string, input: JsonObject, actorId: string, idempotencyKey: string, now = Date.now()): Record<string, unknown> { this.requireFeature("agent_work_teaching_enabled"); throw new Error("CAPABILITY_UNAVAILABLE"); }

  getOperation(id: string): Record<string, unknown> | undefined { const row = this.db.one<Row>("SELECT * FROM agent_operations WHERE id = ?", id); return row ? this.operationProjection(row) : undefined; }
  eventsPage(afterSeq = 0, limit = 100): Record<string, unknown> { const safeLimit = Math.min(200, Math.max(1, limit)); const rows = this.db.all<Row>("SELECT * FROM agent_events WHERE seq > ? ORDER BY seq LIMIT ?", Math.max(0, afterSeq), safeLimit + 1); const items = rows.slice(0, safeLimit).map((row) => ({ seq: Number(row.seq), eventId: row.event_id, producerId: row.producer_id, sourceKey: row.source_key, subjectKind: row.subject_kind, subjectId: row.subject_id, subjectRevision: Number(row.subject_revision), type: row.type, payload: parseJson(row.payload_json), createdAt: iso(row.created_at) })); return { items, nextSeq: items.length ? items.at(-1)!.seq : Math.max(0, afterSeq), hasMore: rows.length > items.length, snapshotSeq: Number(this.db.one<Row>("SELECT COALESCE(MAX(seq), 0) AS value FROM agent_events")?.value ?? 0) }; }

  private requireFeature(flag: string): void { if ((this.settings.get() as Row)[flag] !== true) throw new Error("FEATURE_DISABLED"); }
  private requireOffice(id: string): void { if (!this.db.one("SELECT id FROM offices WHERE id = ? AND archived_at IS NULL", id)) throw new Error("OFFICE_NOT_FOUND"); }
  private requireArtifact(id: string, expectedHash: string): Row { const row = this.db.one<Row>("SELECT * FROM artifacts WHERE id = ?", id); if (!row) throw new Error("ARTIFACT_NOT_FOUND"); if (String(row.sha256) !== expectedHash) throw new Error("ARTIFACT_CONTENT_CONFLICT"); if (String(row.storage_state ?? "AVAILABLE") !== "AVAILABLE" || !this.artifacts.exists(String(row.storage_path))) throw new Error("ARTIFACT_MISSING"); if (ArtifactStorage.digest(this.artifacts.read(String(row.storage_path))) !== expectedHash) throw new Error("ARTIFACT_CONTENT_CONFLICT"); return row; }
  private validateSkillSpec(spec: JsonObject): void { if (spec.schema_version !== 1) throw new Error("INVALID_FIELD:spec.schema_version"); const steps = spec.steps; if (!Array.isArray(steps) || steps.length === 0 || steps.length > 50) throw new Error("INVALID_FIELD:spec.steps"); if (JSON.stringify(spec).length > 1_048_576) throw new Error("INVALID_FIELD:spec"); }
  private compatibility(spec: JsonObject): string { return spec.required_capabilities === undefined || Array.isArray(spec.required_capabilities) ? "COMPATIBLE" : "UNKNOWN"; }
  private authorityEpoch(): string { return String(parseJson(this.db.one<Row>("SELECT value_json FROM runtime_metadata WHERE key = 'office_authority_epoch'")?.value_json, "")); }
  private startOperation(kind: string, resourceKind: string, resourceId: string | null, actorId: string, key: string, requestHash: string, request: JsonObject, now: number): { id: string; replayed: boolean; result: Record<string, unknown> } { if (!key || key.length > 200) throw new Error("MISSING_IDEMPOTENCY_KEY"); const scope = `agent-work:${actorId}:${kind}:${resourceId ?? "create"}`; const existing = this.db.one<Row>("SELECT * FROM agent_operations WHERE logical_scope = ? AND idempotency_key = ?", scope, key); if (existing) { if (existing.request_hash !== requestHash) throw new Error("IDEMPOTENCY_CONFLICT"); return { id: String(existing.id), replayed: true, result: parseJson(existing.result_json, {}) }; } const id = uuidv7(now); this.db.run("INSERT INTO agent_operations(id, actor_id, operation_kind, resource_kind, resource_id, logical_scope, idempotency_key, request_hash, request_json, authority_epoch, state, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'ACCEPTED', ?, ?)", id, actorId || "owner", kind, resourceKind, resourceId, scope, key, requestHash, JSON.stringify(request), this.authorityEpoch(), now, now); return { id, replayed: false, result: {} }; }
  private operationResult(id: string): Record<string, unknown> { const row = this.db.one<Row>("SELECT result_json FROM agent_operations WHERE id = ?", id); return parseJson(row?.result_json, { operation_id: id }); }
  private recordOperationApplied(id: string, result: JsonObject, now: number): void { this.db.run("UPDATE agent_operations SET state = 'APPLIED', result_json = ?, revision = revision + 1, updated_at = ? WHERE id = ?", JSON.stringify({ operation_id: id, state: "APPLIED", ...result, observed_at: new Date(now).toISOString() }), now, id); }
  private recordOperationError(id: string, error: unknown, now: number): void { const code = error instanceof Error ? error.message : "INTERNAL_ERROR"; this.db.run("UPDATE agent_operations SET state = 'REJECTED', error_code = ?, result_json = ?, revision = revision + 1, updated_at = ? WHERE id = ?", code, JSON.stringify({ operation_id: id, state: "REJECTED", error: code, observed_at: new Date(now).toISOString() }), now, id); }
  private createCommand(operationId: string, target: string, kind: string, logicalKey: string, envelope: JsonObject, requestHash: string, now: number): void { const id = uuidv7(now); this.db.run("INSERT INTO agent_commands(id, operation_id, target, kind, logical_key, envelope_json, request_hash, transport_state, processing_state, next_send_at, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'PENDING', 'NOT_STARTED', ?, ?)", id, operationId, target, kind, logicalKey, JSON.stringify(envelope), requestHash, now, now); }
  private pinArtifact(ownerKind: string, ownerId: string, ownerVersion: number, artifactId: string, purpose: string, now: number): void { this.db.run("INSERT OR IGNORE INTO agent_artifact_refs(owner_kind, owner_id, owner_version, artifact_id, purpose, metadata_json, pin_state, created_at) VALUES (?, ?, ?, ?, ?, '{}', 'PINNED', ?)", ownerKind, ownerId, ownerVersion, artifactId, purpose, now); }
  private appendEvent(subjectKind: string, subjectId: string, revision: number, type: string, payload: JsonObject, now: number): void { const eventId = uuidv7(now); const sourceKey = `${subjectKind}:${subjectId}:${type}:${revision}`; this.db.run("INSERT OR IGNORE INTO agent_events(event_id, producer_id, source_key, subject_kind, subject_id, subject_revision, type, payload_json, created_at) VALUES (?, 'control-plane', ?, ?, ?, ?, ?, ?, ?)", eventId, sourceKey, subjectKind, subjectId, revision, type, JSON.stringify(payload), now); }
  private operationProjection(row: Row): Record<string, unknown> { return { id: row.id, operationId: row.id, operationKind: row.operation_kind, resourceKind: row.resource_kind, resourceId: row.resource_id, state: row.state, revision: Number(row.revision), result: parseJson(row.result_json, null), errorCode: row.error_code ?? null, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
  private skillProjection(row: Row, detail = false): Record<string, unknown> { const result: Row = { id: row.id, officeId: row.office_id, name: row.name, activeVersion: row.active_version ?? null, revision: Number(row.revision), nextVersion: Number(row.next_version), archivedAt: iso(row.archived_at), updatedAt: iso(row.updated_at) }; if (detail) result.versions = this.db.all<Row>("SELECT * FROM work_skill_versions WHERE skill_id = ? ORDER BY version DESC", row.id).map((version) => this.versionProjection(version)); return result; }
  private versionProjection(row: Row): Record<string, unknown> { return { skillId: row.skill_id, version: Number(row.version), artifactId: row.artifact_id, contentHash: row.content_hash, spec: parseJson(row.spec_json), sourceMissionId: row.source_mission_id ?? null, sourceResultHash: row.source_result_hash ?? null, validationState: row.validation_state, compatibilityState: row.compatibility_state, lifecycle: row.lifecycle, stateRevision: Number(row.state_revision), createdAt: iso(row.created_at) }; }
  private routineProjection(row: Row, detail = false): Record<string, unknown> { const result: Row = { id: row.id, officeId: row.office_id, nativeKey: row.native_key, routineId: row.routine_id ?? null, desiredRevision: Number(row.desired_revision), effectiveRevision: row.effective_revision === null ? null : Number(row.effective_revision), nativeRevision: row.native_revision === null ? null : Number(row.native_revision), remoteState: row.remote_state, syncState: row.sync_state, admissionBlocked: Boolean(row.admission_blocked), nextFireAt: iso(row.next_fire_at), observedAt: iso(row.observed_at), updatedAt: iso(row.updated_at) }; if (detail) { result.revisions = this.db.all<Row>("SELECT * FROM routine_binding_revisions WHERE binding_id = ? ORDER BY revision DESC", row.id).map((item) => ({ revision: Number(item.revision), skillId: item.skill_id, skillVersion: Number(item.skill_version), intent: parseJson(item.intent_json), operationId: item.operation_id, requestHash: item.request_hash, createdAt: iso(item.created_at) })); result.occurrences = this.db.all<Row>("SELECT * FROM routine_occurrences WHERE binding_id = ? ORDER BY received_at DESC LIMIT 100", row.id).map((item) => this.occurrenceProjection(item)); } return result; }
  private occurrenceProjection(row: Row): Record<string, unknown> { return { sourceKey: row.source_key, bindingId: row.binding_id, bindingRevision: Number(row.binding_revision), nativeRevision: Number(row.native_revision), state: row.state, reasonCode: row.reason_code ?? null, missionId: row.mission_id ?? null, scheduledFor: iso(row.scheduled_for), payload: parseJson(row.payload_json), receivedAt: iso(row.received_at), updatedAt: iso(row.updated_at) }; }
  private goalProjection(row: Row, detail = false): Record<string, unknown> { const result: Row = { id: row.id, officeId: row.office_id, title: row.title, objective: parseJson(row.objective_json), scope: parseJson(row.scope_json), limits: parseJson(row.limits_json), state: row.state, health: row.health, revision: Number(row.revision), projectionRevision: Number(row.projection_revision), deadlineAt: iso(row.deadline_at), nextReviewAt: iso(row.next_review_at), reviewState: row.review_state, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; if (detail) { result.milestones = this.db.all<Row>("SELECT * FROM goal_milestones WHERE goal_id = ? ORDER BY ordinal", row.id).map((item) => ({ id: item.id, ordinal: Number(item.ordinal), title: item.title, required: Boolean(item.required), criteria: parseJson(item.criteria_json), state: item.state, acceptance: parseJson(item.acceptance_json, null), revision: Number(item.revision) })); result.missions = this.db.all<Row>("SELECT mission_id, milestone_id, goal_revision, proposal_key, work_fingerprint, blocked_by_goal_control FROM goal_mission_links WHERE goal_id = ?", row.id).map((item) => ({ missionId: item.mission_id, milestoneId: item.milestone_id, goalRevision: Number(item.goal_revision), proposalKey: item.proposal_key, workFingerprint: item.work_fingerprint, blocked: Boolean(item.blocked_by_goal_control) })); } return result; }
  private attentionProjection(row: Row): Record<string, unknown> { return { id: row.id, subjectKind: row.subject_kind, subjectId: row.subject_id, reasonCode: row.reason_code, episode: Number(row.episode), severity: row.severity, state: row.state, revision: Number(row.revision), changeRevision: Number(row.change_revision), fingerprint: row.fingerprint, evidence: parseJson(row.evidence_json), actionRef: parseJson(row.action_ref_json, null), deadlineAt: iso(row.deadline_at), snoozeUntil: iso(row.snooze_until), readThroughRevision: Number(row.read_through_revision), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
  private browserProjection(row: Row): Record<string, unknown> { return { id: row.id, workerId: row.worker_id, brokerId: row.broker_id, profileRef: row.profile_ref, state: row.state, generation: Number(row.generation), revision: Number(row.revision), controller: row.controller, missionRunId: row.mission_run_id ?? null, leaseUntil: iso(row.lease_until), policyHash: row.policy_hash, brokerSnapshotSeq: Number(row.broker_snapshot_seq), observedAt: iso(row.observed_at), updatedAt: iso(row.updated_at) }; }
}
