import type { JsonValue } from "../../../../packages/contracts/src/index.ts";
import type { ExecutionEvent, WorkerExecutor, WorkerTaskOffer } from "../runtime.ts";

export class OllamaExecutor implements WorkerExecutor {
  readonly type = "llm.inference";
  private readonly baseUrl: string;
  private readonly enabled: boolean;
  constructor(baseUrl = "http://127.0.0.1:11434", enabled = true) { this.baseUrl = baseUrl; this.enabled = enabled; }
  canExecute(task: WorkerTaskOffer): boolean { return this.enabled && task.task_type === "llm.inference" && (!task.execution?.runtime || task.execution.runtime === "auto" || task.execution.runtime === "ollama"); }
  async discover(): Promise<{ capabilities: Record<string, JsonValue>[]; models: Record<string, JsonValue>[] }> { if (!this.enabled) return { capabilities: [], models: [] }; try { const response = await fetch(`${this.baseUrl}/api/tags`, { signal: AbortSignal.timeout(1_500) }); if (!response.ok) return { capabilities: [{ capability: "llm.inference", runtime: "ollama", status: "DEGRADED" }], models: [] }; const payload = await response.json() as { models?: Array<Record<string, any>> }; return { capabilities: [{ capability: "llm.inference", runtime: "ollama", status: "READY", max_concurrency: 1 }], models: (payload.models ?? []).map((model) => ({ runtime: "ollama", id: String(model.name), display_name: String(model.name), status: "ready", metadata: { size: Number(model.size ?? 0) } })) }; } catch { return { capabilities: [{ capability: "llm.inference", runtime: "ollama", status: "DEGRADED" }], models: [] }; } }
  async *execute(task: WorkerTaskOffer): AsyncIterable<ExecutionEvent> { const payload = task.payload ?? {}; const model = String((task.execution?.model as any)?.name ?? ""); yield { type: "progress", progress: { phase: "llm.request", runtime: "ollama" } }; const response = await fetch(`${this.baseUrl}/api/chat`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ model, stream: false, messages: [{ role: "system", content: String((payload as any).system_prompt ?? "You are an execution worker.") }, { role: "user", content: String((payload as any).prompt ?? task.instruction) }] }), signal: AbortSignal.timeout(Number(task.limits?.timeout_seconds ?? 1800) * 1_000) }); if (!response.ok) throw new Error(`OLLAMA_HTTP_${response.status}`); const result = await response.json() as Record<string, any>; yield { type: "result", result: { text: String(result.message?.content ?? ""), model, runtime: "ollama" }, metrics: { prompt_tokens: Number(result.prompt_eval_count ?? 0), completion_tokens: Number(result.eval_count ?? 0) } }; }
}
